// Planned episode slate for Petspective.
// Listener-visible titles only — fact-or-fiction prompts and wildcard slots
// live in the producer's episode guide, not in this list.
export const PLANNED_EPISODES: string[] = [
  'What Your Vet Wishes You Knew Before the First Visit',
  "From Your Pet's Perspective: What the Vet Visit Actually Feels Like",
  'Behind the Curtain: What Happens After You Hand Off Your Pet',
  'Why Veterinary Care Costs What It Costs',
  "Why Is My Pet's Bloodwork So Expensive?",
  'How Often Does My Pet Actually Need Bloodwork?',
  'Pet Dentistry 101: Is There Only One Way to Do It?',
  'Why Pet Dentals Cost What They Cost',
  'Does My Dog Need a Cardiologist?',
  'When Does My Pet Need a Specialist?',
  'Can My Dog Get Skin Cancer from the Sun?',
  'The Most Common Cancers in Dogs and Cats',
  'When the C-Word Comes Up: What Happens Next',
  "Vaccines: What's Core, What's Optional, What's Hype",
  'Parasites: The Stuff We Wish You Took Seriously',
  "What Your Pet Thinks About You (According to Vets Who've Watched Thousands of Them)",
  'Spay and Neuter: Timing, Myths, and Real Tradeoffs',
  'Emergency Vet vs. Your Regular Vet: When to Go Where',
  'Pet Insurance: Is It Worth It?',
  'How Vets Actually Set Prices',
  'Why Veterinary Care Got So Much More Expensive',
  'Why Every Visit Has an "Exam Fee"',
  'The Real Cost of an X-Ray, Ultrasound, and CT',
  'Why Anesthesia Drives the Bill',
  'Prescription Diets: Necessary or Nonsense?',
  'Grain-Free, Raw, and Boutique Diets',
  'Allergies: Skin, Food, and Everything In Between',
  'Senior Pets: What Changes and What to Watch For',
  'End of Life: Quality of Life and the Hardest Conversation',
  'Behavior: Training Problems vs. Medical Problems',
  'The Itchy Ear, the Head Tilt, and Other Things You Should Not Google',
  'Vomiting and Diarrhea: When to Wait, When to Worry',
  "Lumps, Bumps, and What's Worth a Biopsy",
  'Dermatology: Skin Is the Biggest Organ and the Biggest Headache',
  'Orthopedics: Limping, ACLs, and Hip Dysplasia',
  'Eyes: Why a Red Eye Is Almost Always Urgent',
  "Toxins in Your House You Don't Think About",
  'Cats Are Not Small Dogs',
  'Exotics 101: Birds, Reptiles, and Pocket Pets',
  'Travel, Boarding, and Daycare: What Vets Actually Recommend',
  'Microchips, IDs, and What Actually Reunites Lost Pets',
  'Vet Tech vs. Vet vs. Vet Assistant: Who Does What',
  'Mental Health in Veterinary Medicine',
  'Online Pharmacies and Where to Actually Buy Pet Meds',
  'Reproductive Health: Breeding, Pyometra, and Why Spaying Is Surgery',
  'Pet Obesity: The Quiet Epidemic',
  'Why Vets Push Heartworm Tests Even on Prevention',
  'Holistic, Integrative, and Acupuncture for Pets',
  "Why Your Estimate and Your Final Bill Don't Match",
  'Wellness Plans, Memberships, and Subscription Vet Care',
  'The Future of Veterinary Medicine',
  'Ask a Vet Anything: Listener-Submitted Marathon'
];
