// Planned episode slate for Petspective.
// Listener-visible titles only — fact-or-fiction prompts and wildcard slots
// live in the producer's episode guide, not in this list.
export const PLANNED_EPISODES: string[] = [
  'What Does Your Pet Experience During a Vet Visit?',
  'The Hidden Health Signs—Subtle Behaviors That Mean More',
  'Nutrition Trends & Pets—Myths vs. Facts',
  'Preventative Care—What It Really Means',
  'The Weirdest Objects Vets Have Removed',
  'How Aging Affects Pets',
  'A Day in the Life of a Vet Tech',
  'Pets’ Emotions Mirror Ours',
  'The Truth About Exotic Pets',
  'Decoding Pet Body Language',
  'How Cats Feel About Their Owners',
  'Doggy Daycare or Home Alone?',
  'Why Pets Hate (or Love) the Vet',
  'From Stray to Family—Adoption Stories',
  'The Reality of Pet Insurance',
  'Can Pets Get Jealous?',
  'The Science of Pet Dreams',
  'How to Travel With Your Pet',
  'Natural Remedies for Pets—Safe or Not?',
  'What Your Dog’s Breed Doesn’t Tell You',
  'Behind the Curtain—What Happens After You Leave?',
  'The Cost of Veterinary Care—Why Is It So Expensive?',
  'Pet Dentistry—Is There Only One Way to Do It?',
  'Does My Dog Need a Specialist (Like a Cardiologist)?',
  'Pet Cancer—Can My Dog Get Skin Cancer From the Sun?',
  'Why Is My Pet’s Bloodwork So Expensive?',
  'How Often Does My Pet Need X-Rays—And Why Are They Pricey?',
  'Prescription Medications—Why Can’t I Just Buy Them Cheaper Elsewhere?',
  'Why Are Surgeries So Expensive for Pets?',
  'Routine Vaccines—Why Do Prices Vary So Much?'
];
